project:
  type: book
  output-dir: docs

execute:
  echo: true
  freeze: auto
  keep-md: false

book:
  title: "Método PDCA e ferramentas da qualidade"
  author: "Marcelo Carvalho dos Anjos"
  search: true
  repo-url: https://github.com/factorialmap/pdca
  date: today
  downloads: [epub]
  sharing: [twitter, facebook, linkedin]
  sidebar: 
    style: docked
    background: light
  reader-mode: true
  bread-crumbs: false
  page-footer:
    left: |
      This book was written by Marcelo Carvalho dos Anjos.
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  cover-image: pdca_capa.PNG
  favicon: pdca_capa.PNG

  chapters:
    - index.qmd
    - intro.qmd
    - conceitos.qmd
    - fluxograma-de-processos.qmd
    - cinco-s.qmd
    - cinco-porques.qmd
    - diagrama-causa-efeito.qmd
    - check-list.qmd
    - grafico-de-dispercao.qmd
    - grafico-pareto.qmd
    - grafico-de-controle.qmd
    - plano-de-acao.qmd
    - relatorio-tres-geracoes.qmd

format:
  html:
    toc: true
    theme: flatly
    code-fold: true
    callout-appearance: simple
    
comments: 
  hypothesis: true


