project:
  type: book
  output-dir: docs

execute:
  echo: true

book:
  title: "Método PDCA e ferramentas da qualidade"
  author: "Marcelo Carvalho dos Anjos"
  repo-url: https://github.com/factorialmap/pdca
  date: today
  page-footer:
    left: |
      O método PDCA e ferramentas da qualidade was written by Marcelo Carvalho dos Anjos.
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  cover-image: pdca_capa.PNG
  favicon: pdca_capa.PNG

  chapters:
    - index.qmd
    - intro.qmd
    - conceitos.qmd
    - fluxograma-de-processos.qmd
    - cinco-s.qmd
    - cinco-porques.qmd
    - diagrama-causa-efeito.qmd
    - check-list.qmd
    - grafico-de-dispercao.qmd
    - grafico-pareto.qmd
    - grafico-de-controle.qmd
    - plano-de-acao.qmd
    - relatorio-tres-geracoes.qmd

format:
  html:
    theme: flatly
    code-fold: true


