# Diagrama de Causa e Efeito(Ishikawa)

## O que é {-}

O diagrama de causa e efeito, diagrama de Ishikawa ou espinha de peixe, é uma ferramenta gráfica que facilita identificar uma relação significativa entre o efeito e suas possíveis causas (WERKEMA, 1995). Muito utilizada no gerenciamento de diversos processos e de diversos projetos. foi originalmente proposto pelo engenheiro químico japonês Kaoru Ishikawa em 1943, e aperfeiçoado nos anos seguintes.

## Qual o objetivo {-}

- Estimular a interação entre as pessoas, ambiente e instrumetos usados na busca de causas que unfluenciam no efeito.

- Permitir que todos os envolvidos contribuam com ideias e pontos de vista.

- Facilitar a identificação de possíveis causas sobre o efeito proposto.


## De onde vem {-}

- A
- B
- C

## Como fazer {-}

- A
- B
- C

## Pra onde vai {-}

- A
- B
- C

## Qual o resultado {-}

- A
- B
- C


Essa ferramenta foi utilizada pela primeira vez no Japão por volta de 1953, com o objetivo de sintetizar as opiniões dos engenheiros de uma fábrica quando estes discutem problemas referentes à qualidade dos produtos (SEBRAE, 2009), 

Esse sistema permite estruturar hierarquicamente as causas de determinado problema ou oportunidade de melhoria, bem como seus efeitos sobre a qualidade dos produtos. Permite também, estruturar qualquer sistema que necessite de resposta de forma gráfica e sintética, obtendo melhor visualização (SEBRAE, 2009).