# Glossário

### Objetivo {.unnumbered}

-   A ideia do glossário é auxiliar o iniciante em sua jornada de aprendizado.
-   Juntando descrição técnica + analogias para que a **ideia do termo utilizado** faça sentido para os que não ainda não possuem familiaridade com ele.
-   Por estar em uma linguagem simples, não significa que o contexto seja simples havendo necessidade de aprofundar-se no tema. Portanto, este é apenas um mecanismo para auxiliar a rede neural biologica(cerebro) **associar** o novo contexto ao contexto usado no dia-a-dia permitindo assim, a entrada e processado da informação através da perspectiva da **associação**. Em resumo seria a percepção **Ahh, agora isso fez sentido!**

**Algorítmo**: Sequencia de instruções usadas para resolver uma classe de problemas específicos como por exemplo realizar cálculos. Em outras palavras, seria um conjunto de regras que define com precisão uma sequencia de operações. O nome é derivado do matemático persa al-Khwarizmi que viveu por volta do ano 813 o qual seus trabalhos estabeleceram as bases da álgebra que leva o nome do seu livro Al-Jabr e também na trigonometria.

**Heurística:** é uma abordagem para resolução de problemas que pode não ser totalmente especificada ou pode não garantir resultados corretos ou ótimos, especialmente em domínios de problemas onde não há um resultado correto ou ótimo bem definido.

**Calibração**: Processo de ajustar um modelo estatístico para que ele seja mais preciso e confiável. Imagine um modelo que tenta prever a probabilidade de fazer sol amanhã. No entanto, o modelo pode estar um pouco desajustado e não refletir bem a realidade e precisar de calibração. Seria como afinar o modelo para que ele seja mais preciso comparando as previsões com os resultados reais, em seguida ajustando os parametros para minimizar os erros. Seria como afinar as cordas de um violão usando um afinador como parametro real.

**Machine learning**:

**Odds ratio**: Medida estatística que compara a probabilidade de um evento ocorrer em dois grupos diferentes. Imagine que você quer saber se comer gorduras aumenta a chance de obesidade. Você compara dois grupos sendo grupo 1 pessoas que comem gordura e grupo 2 pessoas que não comem gordura. O odds ratio é a razão entre as chances de obesidade entre os dois grupos, se for maior que 1 singifica que o evento(obesidade) é mais provável de ocorrer no grupo que come gorduras, se for igual a 1 significa que não há diferença entre os grupos. Por exemplo se o odds ratio for 3, significa que pessoas que comem gorduras tem 3 vezes mais chandes de obesidade do que as pessoas que não comem gorduras. O odds ratio não é uma medida de causa e efeito, mas sim apenas uma forma de comparar a probabilidade de um evento ocorrer em diferentes grupos.

**Correção de Bonferroni**:

**Documento reproduzível**: Documento onde é possível inserir texto, fórmulas matemáticas e códigos de programação e ou instruções que permitam a reprodução por outros pesquisadores.

**Desvio padrão**: Medida de dispersão em torno de uma média. Quanto maior o desvio padrão, maior será a variação em torno da média.

**Erro padrão**:

**Variável binária**: Variável que pode ter apenas dois valores possíveis, geralmente representados por 0 ou 1. Pense em uma pergunta do tipo sim ou não. A resposta pode ser apenas uma das duas opções, ou seja, não há mais escolhas. Como na computação as maquinas trabalham com números essas respostas sao transformadas em números. Sim(1), Não(0), Passa(1), Não passa(0), Defeito(1), Não defeito(0). Essas variáveis são fundamentais da lógica de computadores e são usadas em muitas áreas como programação, estatística e inteligência artificial.

**Falso negativo**:

**Falso positivo**:

**Teste A/B**:

**Teste caso/controle**:

**Grupo controle**:

**Grupo tratamento**:

**Placebo**:

**Sabedoria das multidões**:

**Significancia estatística**: **Hipótese nula**:

**Variável discreta**: É um tipo de variável que é representada por números, ou seja uma quantidade mas que pode ter apenas valores inteiros e se move em saltos. Por exemplo número de filhos, quantidade de veículos que uma pessoa tem, número de lados em um dado. Geralmente esse tipo de variável pode ser contada. Uma regra geral para identificar se a variável é discreta, tente imaginar se alguem teria 3,8 cachorros em casa, ou uma gelaeira e meia, certamente que não. Logo, a varável é discretra.

**Variável contínua**: É um tipo de variável que é representada por números, ou seja uma quantidade que se move lentamente dentro de um intervalo podendo ter valores fracionários ou decimais como a altura de uma pessoa que pode ser 1,75 metros, ou peso de uma melancia que pode ser de 5,7kgs ou a temperatura de uma geladeira que pode ser 5,3 graus.

**Variável dependente**:

**Variável de desfecho**:

**Variável de resposta**:

**Variável independente**:

**Variável preditora**:

**Cp**: Capacidade de processo é uma medida que avalia se um processo é capaz de produtize resultados dentro de limites aceitáveis e consistentes dentro de uma especificação. É calculado com base na variabilidade do processo e nas tolerâncias especificadas. Quando maior o CP, maior a capacidade do processo de produzir resultados dentro da especificação.

Imagine a produção de parafusos com diâmetro especificado de 10 mm e tolerância de 0,5mm. Se o CP é alto, significa que o processo é capaz de produzir parafusos com diâmetros entre 9.5mm e 10,5 mm.

**Cpk**: Capacidade de processo centralizada é uma medida que avalia se um processo é capaz de produzir resultados dentro de limite aceitaveis e consistentes dentro de uma espefificação mas também a centralização dos resultados em relação às especificações. Ela mede a capacidade de um processo de produzir resultados consistentes, dentro das especificações e próximos do valor nominal. É calculado com base na variabilidade do processo, nas tolerâncias especificadas e na centralização dos resultados. Quanto maior o CPK, maior a capacidade do processo de produzir resultados dentro das especificações e próximso do valor nominal.

Imagine a produção de parafusos com diâmetro especificado de 10 mm e tolerância de 0,5mm. Se o CPK é alto, significa que o processo é capaz de produzir parafusos com diâmetros próximos de 10mm, dentro da tolerância de 0,5mm.

**Preditores**:

**Distribuição normal**:

**Distribuição binomial**:

**Distribuição Bernoulli**:

**Distribuição Poisson**:

**Feature engineering**:

**Erro do tipo I**:

**Erro do tipo II**:

**Erro do tipo III**:

**Ponto 1 de Deming**: Crie constancia de propósito para melhorar continuamente produtos e serviços.

**Ponto 3 de Deming**: Opte por melhorar a qualidade ao inves de inspeções em massa.

**Ponto 4 de Deming**: Evite premiar negócios com base no preço inicial. Pense no custo total e quanto as variações influenciam na qualidade.

**Ponto 5 de Deming**: Melhorar constantemente independente do ciclo economico, seja de expansão ou retração.

**Ponto 6 de Deming**: Instituir treinamento de trabalho.

**Ponto 7 de Deming**: Ter em mente que o objetivo da supervisão é ajudar as pessoas, maquinas e dispositivos a fazere um trabalho melhor.

**Ponto 8 de Deming**: Afastar o medo para que todos possam trabalhar de forma eficaz para a empresa.

**Ponto 9 de Deming**: Derrubar barreiras entre departamentos. Promover a cooperação e intetração entre os times de pesquisa, design, vendas e produção.

**Ponto 10 de Deming**: Eliminar slogans e exortações e metas para forçar o trabalho pedindo zero defeitos e novos níveis de produtividade.

**Ponto 11 de Deming**: Eliminar cotas de trabalho no chão da fabrica.

**Ponto 12 de Deming**: Eliminar gestão por objetivos de curto prazo.Remover as barreiras de roubam as pessoas o seu direito ao orgulho do seu trabalho.

**Ponto 13 de Deming**: Instituir programa vigoroso de educação e auto aperfeiçoamento.

**Ponto 14 de Deming**: Colocar todos para trabalhar para realizar a transformação. A transformação é tarefa de todos(Deming, W. Edwards. Fora da crise (MIT Press) (pp. 23-24) )
